# Generated by Django 5.2.1 on 2025-05-17 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_author', '0003_alter_author_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='owner',
        ),
        migrations.AddField(
            model_name='author',
            name='owner',
            field=models.ManyToManyField(default=1, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
